"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Owner={id:string;nif:string;name:string;email:string;phone:string;address:string;postalCode:string;province:string;municipality:string}; type Product={id:string;registration:string;name:string;lot:string;capacity:string;unit:string;packs:string;total:string;parallel:string;common:string}; type Application={id:string;date:string;ownerId:string;productId:string;crop:string;use:string;surface:string;location:string}; type Responsible={nif:string;ropo:string;name:string};
const emptyResponsible:Responsible={nif:"",ropo:"",name:""}; const uid=()=>crypto.randomUUID(); const read=<T,>(key:string,fallback:T):T=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const owner=(id:string,nif:string,name:string):Owner=>({id,nif,name,email:"",phone:"",address:"",postalCode:"",province:"46",municipality:"233"});
const product=(id:string,registration:string,name:string,lot:string,packs:string,total:string):Product=>({id,registration,name,lot,capacity:"5",unit:"3",packs,total,parallel:"N",common:"N"});
const sigpac=(pol:string,parcel:string,recintos:number[])=>recintos.map(r=>`46/235/0/0/${pol.padStart(3,"0")}/${parcel.padStart(5,"0")}/${String(r).padStart(3,"0")}`).join(" · ");
const augustOwners:Owner[]=[
 owner("vicente","22603964R","Vicente Milla Soria"),owner("jose-ballester","22604211M","Jose Ballester Chirivella"),owner("rochets","B98162241","Els Rochets de Pinedo"),owner("elvira","22512934M","Elvira Tomas Sabater"),owner("carmen","22541429A","Carmen Sanchis Alabau"),owner("francisco","22674720D","Francisco Gil Parra"),owner("angel","19496948D","Angel Bosch Ferrus"),owner("arroceria","B46696340","Arroceria Rovira Ballester S.L."),owner("dolores","19790411S","Dolores Muñoz Raga"),owner("jose-antonio","18862632X","Jose Antonio Cherta Prats"),owner("domingo","E46924254","Hermanos Domingo Aleixandre"),owner("gimeno","E97790760","Hermanos Gimeno Vicent"),owner("mocholi","73740830R","Jose Mocholi Baixauli"),owner("josefa","25389031K","Josefa Orobal Cañada"),owner("angela","19460151N","Angela Gil Almiñana"),owner("federico","22529064N","Federico Bayona Bayona")
];
const augustProducts:Product[]=[
 product("p-vicente","25407","AMISTAR TOP","GRA6E00042","0.584","2.92"),product("p-ballester","25407","AMISTAR TOP","GRA5F00042","0.782","3.91"),product("p-rochets","EXCEPCIONAL","TELARON SUPRA","BE26000715","2.332","11.66"),product("p-elvira","ES-01185","SELTIMA","00588536W0","0.116","0.58"),product("p-carmen","ES-01185","SELTIMA","00588536W0","0.116","0.58"),product("p-francisco","ES-01185","SELTIMA","00588536W0","0.184","0.92"),product("p-angel","ES-01185","SELTIMA","00588536W0","0.3","1.5"),product("p-arroceria","ES-01185","SELTIMA","00588536W0","0.284","1.42"),product("p-dolores","ES-01185","SELTIMA","00588536W0","0.15","0.75"),product("p-jose-antonio","25407","AMISTAR TOP","GRA6E00042","0.866","4.33"),product("p-domingo","ES-01185","SELTIMA","00588536W0","0.116","0.58"),product("p-gimeno","ES-01185","SELTIMA","00588536W0","0.3","1.5"),product("p-mocholi","ES-01185","SELTIMA","00588536W0","1","2"),product("p-josefa","ES-01185","SELTIMA","00588536W0","0.316","1.58"),product("p-angela","ES-01185","SELTIMA","00588536W0","1.06","5.3"),product("p-federico","EXCEPCIONAL","TELARON SUPRA","BE26000713","0.4","2")
];
const augustApplications:Application[]=[
 {id:"a-vicente",date:"2026-08-14",ownerId:"vicente",productId:"p-vicente",crop:"ARROZ",use:"A",surface:"2.92",location:[sigpac("21","794",[1]),sigpac("21","307",[1]),sigpac("21","310",[1])].join(" · ")},
 {id:"a-ballester",date:"2026-08-14",ownerId:"jose-ballester",productId:"p-ballester",crop:"ARROZ",use:"A",surface:"3.91",location:[sigpac("26","91",[1,2]),sigpac("21","860",[1]),sigpac("21","309",[1,2,3]),sigpac("21","308",[1])].join(" · ")},
 {id:"a-rochets",date:"2026-08-12",ownerId:"rochets",productId:"p-rochets",crop:"ARROZ",use:"A",surface:"5.83",location:[sigpac("28","90",[1]),sigpac("28","98",[1,2])].join(" · ")},
 {id:"a-elvira",date:"2026-08-11",ownerId:"elvira",productId:"p-elvira",crop:"ARROZ",use:"A",surface:"0.58",location:sigpac("8","735",[1])},
 {id:"a-carmen",date:"2026-08-11",ownerId:"carmen",productId:"p-carmen",crop:"ARROZ",use:"A",surface:"0.58",location:sigpac("8","614",[1,2])},
 {id:"a-francisco",date:"2026-08-10",ownerId:"francisco",productId:"p-francisco",crop:"ARROZ",use:"A",surface:"0.92",location:sigpac("9","174",[1])},
 {id:"a-angel",date:"2026-08-10",ownerId:"angel",productId:"p-angel",crop:"ARROZ",use:"A",surface:"1.5",location:[sigpac("22","53",[1,2,3]),sigpac("22","54",[3,4,6]),sigpac("22","113",[1]),sigpac("22","57",[1]),sigpac("16","54",[1]),sigpac("16","113",[1,2]),sigpac("27","53",[1]),sigpac("27","54",[1]),sigpac("27","57",[1])].join(" · ")},
 {id:"a-arroceria",date:"2026-08-08",ownerId:"arroceria",productId:"p-arroceria",crop:"ARROZ",use:"A",surface:"1.42",location:[sigpac("28","90",[1]),sigpac("28","98",[1,2])].join(" · ")},
 {id:"a-dolores",date:"2026-08-07",ownerId:"dolores",productId:"p-dolores",crop:"ARROZ",use:"A",surface:"0.75",location:sigpac("21","882",[1,2])},
 {id:"a-jose-antonio",date:"2026-08-06",ownerId:"jose-antonio",productId:"p-jose-antonio",crop:"ARROZ",use:"A",surface:"4.33",location:[sigpac("16","517",[1]),sigpac("16","437",[1,2]),sigpac("16","436",[1,2]),sigpac("21","187",[1]),sigpac("21","189",[1])].join(" · ")},
 {id:"a-domingo",date:"2026-08-06",ownerId:"domingo",productId:"p-domingo",crop:"ARROZ",use:"A",surface:"0.58",location:sigpac("16","35",[1])},
 {id:"a-gimeno",date:"2026-08-05",ownerId:"gimeno",productId:"p-gimeno",crop:"ARROZ",use:"A",surface:"1.5",location:[sigpac("11","1",[1]),sigpac("11","5",[1])].join(" · ")},
 {id:"a-mocholi",date:"2026-08-04",ownerId:"mocholi",productId:"p-mocholi",crop:"ARROZ",use:"A",surface:"2",location:[sigpac("13","22",[1,2,3,4]),sigpac("13","54",[1,2])].join(" · ")},
 {id:"a-josefa",date:"2026-08-04",ownerId:"josefa",productId:"p-josefa",crop:"ARROZ",use:"A",surface:"1.58",location:[sigpac("16","322",[1]),sigpac("16","480",[1])].join(" · ")},
 {id:"a-angela",date:"2026-08-04",ownerId:"angela",productId:"p-angela",crop:"ARROZ",use:"A",surface:"5.3",location:[sigpac("14","1",[1]),sigpac("14","9",[1]),sigpac("14","13",[1])].join(" · ")},
 {id:"a-federico",date:"2026-08-03",ownerId:"federico",productId:"p-federico",crop:"ARROZ",use:"A",surface:"1",location:sigpac("8","12",[1])}
];

export default function Home(){
 const [tab,setTab]=useState("inicio"),[ready,setReady]=useState(false),[responsible,setResponsible]=useState<Responsible>(emptyResponsible),[owners,setOwners]=useState<Owner[]>([]),[products,setProducts]=useState<Product[]>([]),[applications,setApplications]=useState<Application[]>([]),[notice,setNotice]=useState(""),[editingOwner,setEditingOwner]=useState<Owner|null>(null),[selectedOwnerId,setSelectedOwnerId]=useState("");
 useEffect(()=>{const savedOwners=read<Owner[]>("reto-owners",[]),savedProducts=read<Product[]>("reto-products",[]),savedApplications=read<Application[]>("reto-applications",[]);if(!savedOwners.length&&!savedProducts.length&&!savedApplications.length){setResponsible({nif:"24343602B",ropo:"104601661ST",name:"Tomas Blanch Baixauli"});setOwners(augustOwners);setProducts(augustProducts);setApplications(augustApplications);setNotice("Se han cargado 16 tratamientos de agosto. Faltan los datos de contacto de los titulares.")}else{setResponsible(read("reto-responsible",emptyResponsible));setOwners(savedOwners);setProducts(savedProducts);setApplications(savedApplications)}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("reto-responsible",JSON.stringify(responsible))},[responsible,ready]);useEffect(()=>{if(ready)localStorage.setItem("reto-owners",JSON.stringify(owners))},[owners,ready]);useEffect(()=>{if(ready)localStorage.setItem("reto-products",JSON.stringify(products))},[products,ready]);useEffect(()=>{if(ready)localStorage.setItem("reto-applications",JSON.stringify(applications))},[applications,ready]);
 const validCount=useMemo(()=>applications.filter(a=>{const o=owners.find(x=>x.id===a.ownerId);return Boolean(responsible.nif&&responsible.ropo&&a.ownerId&&a.productId&&a.date&&a.crop&&a.use&&a.surface&&a.location&&!a.location.includes(" · ")&&o?.address&&o?.postalCode&&(o.email||o.phone))}).length,[applications,responsible,owners]);
 const addOwner=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),data={id:editingOwner?.id||uid(),nif:String(f.get("nif")),name:String(f.get("name")),email:String(f.get("email")),phone:String(f.get("phone")),address:String(f.get("address")),postalCode:String(f.get("postalCode")),province:String(f.get("province")),municipality:String(f.get("municipality"))};setOwners(x=>editingOwner?x.map(o=>o.id===editingOwner.id?data:o):[...x,data]);setEditingOwner(null);e.currentTarget.reset();setNotice(editingOwner?"Titular actualizado.":"Titular guardado.")};
 const addProduct=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setProducts(x=>[...x,{id:uid(),registration:String(f.get("registration")),name:String(f.get("name")),lot:String(f.get("lot")),capacity:String(f.get("capacity")),unit:String(f.get("unit")),packs:String(f.get("packs")),total:String(f.get("total")),parallel:String(f.get("parallel")),common:String(f.get("common"))}]);e.currentTarget.reset();setNotice("Producto guardado.")};
 const addApplication=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setApplications(x=>[...x,{id:uid(),date:String(f.get("date")),ownerId:String(f.get("ownerId")),productId:String(f.get("productId")),crop:String(f.get("crop")),use:String(f.get("use")),surface:String(f.get("surface")),location:String(f.get("location"))}]);e.currentTarget.reset();setNotice("Aplicación preparada para exportar.")};
 const exportCsv=()=>{const ready=applications.filter(a=>{const o=owners.find(x=>x.id===a.ownerId);return Boolean(o?.address&&o?.postalCode&&(o.email||o.phone)&&!a.location.includes(" · "))});if(!ready.length){setNotice("No exporto todavía: faltan datos de contacto o hay varias localizaciones por aplicación.");return}const lines=["RT0001"];ready.forEach(a=>{const o=owners.find(x=>x.id===a.ownerId),p=products.find(x=>x.id===a.productId);if(!o||!p)return;const date=a.date.split("-").reverse().join("/");lines.push(["1",date,responsible.nif,responsible.ropo,"8",o.nif,"",o.name,o.email,o.phone,"",o.address,o.postalCode.padStart(5,"0"),"ES",o.province.padStart(2,"0"),o.municipality.padStart(3,"0"),"","","","",""].join(";"));lines.push(["2",p.registration,p.name,p.lot,p.capacity,p.unit,p.packs,p.total,p.parallel,p.common,a.crop,a.use,a.surface,a.location].join(";"))});const blob=new Blob([encodeWindows1252(lines.join("\r\n")+"\r\n")],{type:"text/csv;charset=windows-1252"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`RETO_aplicaciones_${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);setNotice(`${ready.length} aplicación(es) exportada(s).`)};
 const nav=[['inicio','Resumen'],['responsable','Mi ROPO'],['titulares','Titulares'],['productos','Productos'],['aplicaciones','Aplicaciones']];
 return <main><header><div className="brand"><span>RETO</span><small>cuaderno de aplicaciones</small></div><div className="privacy">Los datos se guardan solo en este navegador</div></header><section className="hero"><p className="eyebrow">Gestión sencilla · RT0001</p><h1>Todo listo para<br/><em>comunicar a RETO.</em></h1><p>Guarda tus fichas una vez. Después solo registra cada aplicación y descarga el CSV.</p><button className="primary" onClick={()=>setTab("aplicaciones")}>Registrar una aplicación <b>→</b></button></section><nav>{nav.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?"active":""}>{label}</button>)}</nav>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 {tab==="inicio"&&<section className="content dashboard"><div className="intro"><p className="eyebrow">Vista general</p><h2>Tu información operativa</h2><p>Las tres fichas son la base. La ficha de aplicación las conecta con los datos que cambian cada día.</p></div><div className="cards"><Card value={responsible.ropo?"Listo":"Pendiente"} label="Mi código ROPO" action={()=>setTab("responsable")}/><Card value={String(owners.length)} label="Titulares registrados" action={()=>setTab("titulares")}/><Card value={String(products.length)} label="Productos registrados" action={()=>setTab("productos")}/><Card value={String(applications.length)} label="Aplicaciones" action={()=>setTab("aplicaciones")}/></div><div className="export"><div><p className="eyebrow">Archivo RT0001</p><h3>{validCount} de {applications.length} aplicaciones listas</h3><p>He cargado agosto, pero el CSV queda bloqueado hasta añadir dirección, código postal y un contacto de cada titular, y separar las aplicaciones con varios recintos.</p></div><button className="primary" disabled={!validCount} onClick={exportCsv}>Descargar CSV <b>↓</b></button></div></section>}
 {tab==="responsable"&&<section className="content form-page"><p className="eyebrow">Ficha 01</p><h2>Quien comunica a RETO</h2><p>Estos datos se reutilizan en cada archivo exportado.</p><div className="form-grid"><Field label="Nombre o razón social" value={responsible.name} onChange={v=>setResponsible({...responsible,name:v})}/><Field label="NIF / CIF" value={responsible.nif} onChange={v=>setResponsible({...responsible,nif:v})}/><Field label="Código ROPO" value={responsible.ropo} onChange={v=>setResponsible({...responsible,ropo:v})}/></div></section>}
 {tab==="titulares"&&<section className="content split"><div><p className="eyebrow">Ficha 02</p><h2>{editingOwner?"Editar titular":"Titulares de las tierras"}</h2><p>{editingOwner?"Actualiza los datos y guarda los cambios.":"La persona o entidad a la que se realiza el tratamiento."}</p><form key={editingOwner?.id||"nuevo"} onSubmit={addOwner} className="form-grid"><Input name="name" label="Nombre o razón social" required defaultValue={editingOwner?.name}/><Input name="nif" label="NIF / CIF" required defaultValue={editingOwner?.nif}/><Input name="email" label="Email" defaultValue={editingOwner?.email}/><Input name="phone" label="Teléfono" defaultValue={editingOwner?.phone}/><Input name="address" label="Dirección" defaultValue={editingOwner?.address}/><Input name="postalCode" label="Código postal" defaultValue={editingOwner?.postalCode}/><Input name="province" label="Provincia INE (ej. 28)" defaultValue={editingOwner?.province}/><Input name="municipality" label="Municipio INE (ej. 079)" defaultValue={editingOwner?.municipality}/><button className="primary">{editingOwner?"Guardar cambios":"Guardar titular"}</button>{editingOwner&&<button type="button" className="secondary" onClick={()=>setEditingOwner(null)}>Cancelar</button>}</form></div><Records title="Titulares guardados" items={owners} text={o=>`${o.name} · ${o.nif}${!o.address||!(o.email||o.phone)?" · contacto pendiente":""}`} remove={id=>setOwners(x=>x.filter(o=>o.id!==id))} edit={id=>setEditingOwner(owners.find(o=>o.id===id)||null)}/></section>}
 {tab==="productos"&&<section className="content split"><div><p className="eyebrow">Ficha 03</p><h2>Productos fitosanitarios</h2><p>Comprueba que registro y nombre comercial coinciden con Aspafitos.</p><form onSubmit={addProduct} className="form-grid"><Input name="registration" label="Nº registro MAPA" required/><Input name="name" label="Nombre comercial" required/><Input name="lot" label="Lote" required/><Input name="capacity" label="Capacidad por envase" required/><Select name="unit" label="Unidad" options={[["1","Gramos"],["2","Kilogramos"],["3","Litros"],["4","Miligramos/unidades"],["5","Mililitros"],["6","CC"]]}/><Input name="packs" label="Nº envases" required/><Input name="total" label="Volumen total" required/><Select name="parallel" label="Importación paralela" options={[["N","No"],["S","Sí"]]}/><Select name="common" label="Denominación común" options={[["N","No"],["S","Sí"]]}/><button className="primary">Guardar producto</button></form></div><Records title="Productos guardados" items={products} text={p=>`${p.name} · ${p.registration}`} remove={id=>setProducts(x=>x.filter(p=>p.id!==id))}/></section>}
 {tab==="aplicaciones"&&<section className="content split"><div><p className="eyebrow">Registro operativo</p><h2>Nueva aplicación</h2><p>Al elegir un titular se cargarán su superficie y todos los recintos SIGPAC conocidos.</p>{(!owners.length||!products.length)&&<div className="hint">Primero añade al menos un titular y un producto.</div>}<form key={selectedOwnerId||"sin-titular"} onSubmit={addApplication} className="form-grid"><Input name="date" label="Fecha" type="date" required/><label>Titular tratado<select name="ownerId" required value={selectedOwnerId} onChange={e=>setSelectedOwnerId(e.target.value)}><option value="">Selecciona…</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name} · {o.nif}</option>)}</select></label><Select name="productId" label="Producto aplicado" options={products.map(p=>[p.id,`${p.name} · ${p.lot}`])}/><Input name="crop" label="Cultivo u objeto de tratamiento" required defaultValue="ARROZ"/><Select name="use" label="Tipo de uso" defaultValue="A" options={[["A","Agrario"],["N","No agrario"]]}/><Input name="surface" label="Superficie (ha)" required readOnly defaultValue={applications.find(a=>a.ownerId===selectedOwnerId)?.surface||""}/><Input name="location" label="SIGPAC o coordenadas GPS" required readOnly defaultValue={applications.find(a=>a.ownerId===selectedOwnerId)?.location||""}/><button className="primary" disabled={!owners.length||!products.length}>Guardar aplicación</button></form></div><Records title="Aplicaciones registradas" items={applications} text={a=>`${a.date.split("-").reverse().join("/")} · ${owners.find(o=>o.id===a.ownerId)?.name||"Titular"}`} remove={id=>setApplications(x=>x.filter(a=>a.id!==id))}/></section>}</main>
}
function Card({value,label,action}:{value:string;label:string;action:()=>void}){return <button className="card" onClick={action}><strong>{value}</strong><span>{label}</span><i>→</i></button>};function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)}/></label>};function Input({label,...props}:{label:string;name:string;required?:boolean;type?:string;defaultValue?:string;readOnly?:boolean}){return <label>{label}<input {...props}/></label>};function Select({label,name,options,defaultValue}:{label:string;name:string;options:string[][];defaultValue?:string}){return <label>{label}<select name={name} required defaultValue={defaultValue}><option value="">Selecciona…</option>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>};function Records<T extends{id:string}>({title,items,text,remove,edit}:{title:string;items:T[];text:(item:T)=>string;remove:(id:string)=>void;edit?:(id:string)=>void}){return <aside className="records"><p className="eyebrow">{title}</p>{items.length?<ul>{items.map(i=><li key={i.id}><span>{text(i)}</span>{edit&&<button onClick={()=>edit(i.id)} aria-label="Editar">Editar</button>}<button onClick={()=>remove(i.id)} aria-label="Eliminar">×</button></li>)}</ul>:<p className="empty">Aún no hay fichas guardadas.</p>}</aside>}
function encodeWindows1252(value:string){const special:{[key:number]:number}={0x20ac:0x80,0x201a:0x82,0x192:0x83,0x201e:0x84,0x2026:0x85,0x2020:0x86,0x2021:0x87,0x2c6:0x88,0x2030:0x89,0x160:0x8a,0x2039:0x8b,0x152:0x8c,0x17d:0x8e,0x2018:0x91,0x2019:0x92,0x201c:0x93,0x201d:0x94,0x2022:0x95,0x2013:0x96,0x2014:0x97,0x2dc:0x98,0x2122:0x99,0x161:0x9a,0x203a:0x9b,0x153:0x9c,0x17e:0x9e,0x178:0x9f};return Uint8Array.from(Array.from(value,c=>{const n=c.codePointAt(0)!;return n<=0xff?n:(special[n]??0x3f)}))}
