"use client";

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";

type Land = { id: string; surface: string; location: string };
type Responsible = { nif: string; ropo: string; name: string };
type Owner = { id: string; nif: string; name: string; email: string; phone: string; address: string; postalCode: string; province: string; municipality: string; hasRopo: boolean; lands: Land[] };
type Product = { id: string; registration: string; name: string; lot: string; dosePerHa: string; unit: string };
type Application = { id: string; date: string; ownerId: string; productId: string; crop: string; use: string };
type Data = { responsible: Responsible; owners: Owner[]; products: Product[]; applications: Application[] };
type LegacyApplication = Partial<Application> & { surface?: string; location?: string; landId?: string };
type LegacyProduct = Partial<Product> & { capacity?: string; packs?: string; total?: string; parallel?: string; common?: string };

const uid = () => crypto.randomUUID();
const empty: Data = { responsible: { nif: "", ropo: "", name: "" }, owners: [], products: [], applications: [] };
const blankOwner = (): Owner => ({ id: uid(), nif: "", name: "", email: "", phone: "", address: "", postalCode: "", province: "46", municipality: "233", hasRopo: false, lands: [] });
const blankProduct = (): Product => ({ id: uid(), registration: "", name: "", lot: "", dosePerHa: "", unit: "3" });
const blankApplication = (): Application => ({ id: uid(), date: new Date().toISOString().slice(0, 10), ownerId: "", productId: "", crop: "ARROZ", use: "A" });
const number = (value: string | number | undefined) => Number(String(value ?? "").replace(",", ".")) || 0;
const decimal = (value: number) => value.toFixed(2).replace(/\.00$/, "").replace(/(\.\d)0$/, "$1");
const csvDecimal = (value: number) => decimal(value).replace(".", ",");
const locationCode = (value: string) => value.replace(/[^a-zA-Z0-9]/g, "");

function normalize(raw: Partial<Data>): Data {
  const oldApplications = Array.isArray(raw.applications) ? raw.applications as LegacyApplication[] : [];
  const owners = (Array.isArray(raw.owners) ? raw.owners : []).map((item) => {
    const source = item as Partial<Owner>;
    const migrated = oldApplications.filter((app) => app.ownerId === source.id && app.location).map((app) => ({ id: uid(), surface: app.surface || "", location: app.location || "" }));
    return { ...blankOwner(), ...source, id: source.id || uid(), hasRopo: Boolean(source.hasRopo), lands: Array.isArray(source.lands) ? source.lands : migrated };
  });
  const products = (Array.isArray(raw.products) ? raw.products : []).map((item) => {
    const source = item as LegacyProduct;
    const related = oldApplications.find((app) => app.productId === source.id);
    const inferredDose = source.dosePerHa || (source.total && related?.surface ? decimal(number(source.total) / number(related.surface)) : "");
    return { ...blankProduct(), id: source.id || uid(), registration: source.registration || "", name: source.name || "", lot: source.lot || "", dosePerHa: inferredDose, unit: source.unit || "3" };
  });
  return { responsible: { ...empty.responsible, ...(raw.responsible || {}) }, owners, products, applications: oldApplications.map((item) => ({ ...blankApplication(), ...item, id: item.id || uid(), crop: item.crop || "ARROZ", use: item.use || "A" })) };
}

function read(): Data { try { return normalize(JSON.parse(localStorage.getItem("reto-data") || "null") || empty); } catch { return empty; } }
function download(content: string | Uint8Array, filename: string, type: string) { const blob = new Blob([content as BlobPart], { type }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
function windows1252(value: string) { const special: Record<number, number> = { 0x20ac: 0x80, 0x201a: 0x82, 0x192: 0x83, 0x201e: 0x84, 0x2026: 0x85, 0x2020: 0x86, 0x2021: 0x87, 0x2c6: 0x88, 0x2030: 0x89, 0x160: 0x8a, 0x2039: 0x8b, 0x152: 0x8c, 0x17d: 0x8e, 0x2018: 0x91, 0x2019: 0x92, 0x201c: 0x93, 0x201d: 0x94, 0x2022: 0x95, 0x2013: 0x96, 0x2014: 0x97, 0x2dc: 0x98, 0x2122: 0x99, 0x161: 0x9a, 0x203a: 0x9b, 0x153: 0x9c, 0x17e: 0x9e, 0x178: 0x9f }; return Uint8Array.from(Array.from(value, (char) => { const code = char.codePointAt(0)!; return code <= 0xff ? code : (special[code] ?? 0x3f); })); }

export default function Home() {
  const [data, setData] = useState<Data>(empty);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState("inicio");
  const [notice, setNotice] = useState("");
  const [editOwner, setEditOwner] = useState<Owner | null>(null);
  const [editProduct, setEditProduct] = useState<Product | null>(null);
  const [application, setApplication] = useState<Application>(blankApplication());
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => { setData(read()); setReady(true); }, []);
  useEffect(() => { if (ready) localStorage.setItem("reto-data", JSON.stringify(data)); }, [data, ready]);

  const selectedOwner = data.owners.find((owner) => owner.id === application.ownerId);
  const selectedProduct = data.products.find((product) => product.id === application.productId);
  const totalSurface = selectedOwner?.lands.reduce((sum, land) => sum + number(land.surface), 0) || 0;
  const totalProduct = totalSurface * number(selectedProduct?.dosePerHa);
  const applicationReady = (item: Application) => {
    const owner = data.owners.find((candidate) => candidate.id === item.ownerId);
    const product = data.products.find((candidate) => candidate.id === item.productId);
    return Boolean(data.responsible.nif && data.responsible.ropo && owner?.lands.length && owner.lands.every((land) => number(land.surface) >= 0.5 && number(land.surface) <= 1000 && locationCode(land.location).length > 0 && locationCode(land.location).length <= 20) && product?.registration && product.name && product.lot && number(product.dosePerHa) > 0 && product.unit && (owner.hasRopo || (owner.address && owner.postalCode && (owner.phone || owner.email))));
  };
  const valid = data.applications.filter(applicationReady).length;

  const importJson = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = () => { try { const parsed = JSON.parse(String(reader.result)); if (!parsed.responsible || !Array.isArray(parsed.owners) || !Array.isArray(parsed.products)) throw new Error(); const imported = normalize(parsed); setData({ ...imported, applications: [] }); setNotice("Datos repetitivos cargados. Las aplicaciones empiezan vacías."); setTab("inicio"); } catch { setNotice("El JSON no tiene el formato esperado."); } event.target.value = ""; };
    reader.readAsText(file);
  };
  const saveBase = () => download(JSON.stringify({ responsible: data.responsible, owners: data.owners, products: data.products }, null, 2), "copia-datos-repetitivos-reto.json", "application/json");
  const saveOwner = (value: Owner) => { setData((current) => ({ ...current, owners: current.owners.some((item) => item.id === value.id) ? current.owners.map((item) => item.id === value.id ? value : item) : [...current.owners, value] })); setEditOwner(null); setNotice("Titular guardado."); };
  const saveProduct = (value: Product) => { setData((current) => ({ ...current, products: current.products.some((item) => item.id === value.id) ? current.products.map((item) => item.id === value.id ? value : item) : [...current.products, value] })); setEditProduct(null); setNotice("Producto guardado."); };
  const saveApplication = (event: FormEvent) => { event.preventDefault(); if (!selectedOwner?.lands.length || !selectedProduct) { setNotice("Elige un titular con tierras registradas y un producto."); return; } const exists = data.applications.some((item) => item.id === application.id); setData((current) => ({ ...current, applications: exists ? current.applications.map((item) => item.id === application.id ? application : item) : [...current.applications, application] })); setApplication(blankApplication()); setNotice(exists ? "Aplicación actualizada." : "Aplicación añadida con todas las tierras del titular."); };
  const exportCsv = () => {
    const applications = data.applications.filter(applicationReady); const rows = ["RT0001"];
    applications.forEach((item) => { const owner = data.owners.find((candidate) => candidate.id === item.ownerId)!; const product = data.products.find((candidate) => candidate.id === item.productId)!; rows.push(["1", item.date.split("-").reverse().join("/"), data.responsible.nif, data.responsible.ropo, "8", owner.nif, "", owner.name, owner.email, owner.phone, "", owner.address, owner.postalCode.padStart(5, "0"), "ES", owner.province.padStart(2, "0"), owner.municipality.padStart(3, "0"), "", "", "", "", ""].join(";")); owner.lands.forEach((land) => rows.push(["2", product.registration, product.name, product.lot, "", product.unit, "", csvDecimal(number(product.dosePerHa) * number(land.surface)), "N", "N", item.crop, item.use, csvDecimal(number(land.surface)), locationCode(land.location)].join(";"))); });
    download(windows1252(`${rows.join("\r\n")}\r\n`), `RETO_aplicaciones_${new Date().toISOString().slice(0, 10)}.csv`, "text/csv;charset=windows-1252"); setNotice(applications.length === data.applications.length ? `${applications.length} aplicación(es) exportada(s).` : `${applications.length} exportada(s); revisa las fichas no válidas.`);
  };

  return <main>
    <header><div className="brand">RETO <small>Cuaderno de aplicaciones</small></div><div>Datos privados en tu navegador</div></header>
    <section className="hero"><p>Importación segura · RT0001</p><h1>Tu cuaderno,<br /><em>en tu propio archivo.</em></h1><p>Carga tu comunicador, titulares, tierras y productos. Las aplicaciones siempre se crean desde cero.</p><button className="primary" onClick={() => fileRef.current?.click()}>Cargar datos JSON</button> <button onClick={saveBase} disabled={!data.owners.length}>Descargar datos JSON</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={importJson} /></section>
    <nav>{[["inicio", "Resumen"], ["comunicador", "Comunicador"], ["titulares", "Titulares"], ["productos", "Productos"], ["aplicaciones", "Aplicaciones"]].map(([id, label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav>
    {notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {tab === "inicio" && <section><h2>Datos preparados</h2><div className="cards"><Card value={data.owners.length} label="Titulares" /><Card value={data.products.length} label="Productos" /><Card value={data.applications.length} label="Aplicaciones" /><Card value={valid} label="Listas para CSV" /></div><button className="primary" disabled={!valid} onClick={exportCsv}>Descargar CSV</button></section>}
    {tab === "comunicador" && <ResponsibleEditor value={data.responsible} save={(responsible) => { setData((current) => ({ ...current, responsible })); setNotice("Comunicador guardado."); }} />}
    {tab === "titulares" && <section className="split"><OwnerEditor key={editOwner?.id || "new-owner"} value={editOwner || blankOwner()} save={saveOwner} cancel={() => setEditOwner(null)} /><Saved title="Titulares" description="El JSON carga estas fichas igual que si las hubieras introducido a mano." onNew={() => setEditOwner(blankOwner())}><List items={data.owners} text={(owner) => `${owner.name} · ${owner.nif} · ${owner.lands.length} tierra(s)`} edit={setEditOwner} remove={(owner) => setData((current) => ({ ...current, owners: current.owners.filter((item) => item.id !== owner.id), applications: current.applications.filter((item) => item.ownerId !== owner.id) }))} /></Saved></section>}
    {tab === "productos" && <section className="split"><ProductEditor key={editProduct?.id || "new-product"} value={editProduct || blankProduct()} save={saveProduct} cancel={() => setEditProduct(null)} /><Saved title="Productos" description="La dosis por hectárea se reutiliza para calcular automáticamente cada aplicación." onNew={() => setEditProduct(blankProduct())}><List items={data.products} text={(product) => `${product.name} · ${product.registration} · ${product.dosePerHa || "—"} ${unitLabel(product.unit)}/ha`} edit={setEditProduct} remove={(product) => setData((current) => ({ ...current, products: current.products.filter((item) => item.id !== product.id), applications: current.applications.filter((item) => item.productId !== product.id) }))} /></Saved></section>}
    {tab === "aplicaciones" && <section className="split"><form onSubmit={saveApplication}><h2>{data.applications.some((item) => item.id === application.id) ? "Editar aplicación" : "Nueva aplicación"}</h2><p>Al seleccionar el titular se incluyen automáticamente todas sus tierras registradas.</p><Fields><label>Fecha<input required type="date" value={application.date} onChange={(event) => setApplication({ ...application, date: event.target.value })} /></label><label>Titular<select required value={application.ownerId} onChange={(event) => setApplication({ ...application, ownerId: event.target.value })}><option value="">Selecciona…</option>{data.owners.map((owner) => <option value={owner.id} key={owner.id}>{owner.name}</option>)}</select></label><label>Producto<select required value={application.productId} onChange={(event) => setApplication({ ...application, productId: event.target.value })}><option value="">Selecciona…</option>{data.products.map((product) => <option value={product.id} key={product.id}>{product.name} · {product.lot}</option>)}</select></label><label>Cultivo<input disabled value="ARROZ" /></label><label>Tipo de uso<select value={application.use} onChange={(event) => setApplication({ ...application, use: event.target.value })}><option value="A">Agrario</option><option value="N">No agrario</option></select></label><label>Superficie total<input readOnly value={selectedOwner ? `${decimal(totalSurface)} ha` : ""} /></label><label>Dosis por hectárea<input readOnly value={selectedProduct ? `${selectedProduct.dosePerHa} ${unitLabel(selectedProduct.unit)}/ha` : ""} /></label><label>Volumen total calculado<input readOnly value={selectedProduct && selectedOwner ? `${decimal(totalProduct)} ${unitLabel(selectedProduct.unit)}` : ""} /></label></Fields>{selectedOwner && <div className="hint"><strong>Tierras incluidas automáticamente:</strong>{selectedOwner.lands.length ? <ul>{selectedOwner.lands.map((land) => <li key={land.id}>{land.surface} ha · {land.location}</li>)}</ul> : <p>Este titular todavía no tiene tierras registradas.</p>}</div>}<button className="primary">{data.applications.some((item) => item.id === application.id) ? "Guardar cambios" : "Añadir aplicación"}</button></form><Saved title={`${data.applications.length} aplicaciones`} description="Puedes editarlas antes de descargar el CSV."><List items={data.applications} text={(item) => { const owner = data.owners.find((candidate) => candidate.id === item.ownerId); const product = data.products.find((candidate) => candidate.id === item.productId); const surface = owner?.lands.reduce((sum, land) => sum + number(land.surface), 0) || 0; return `${item.date.split("-").reverse().join("/")} · ${owner?.name || ""} · ${decimal(surface * number(product?.dosePerHa))} ${unitLabel(product?.unit || "3")}`; }} edit={setApplication} remove={(item) => setData((current) => ({ ...current, applications: current.applications.filter((candidate) => candidate.id !== item.id) }))} /></Saved></section>}
  </main>;
}

function unitLabel(value: string) { return ({ "1": "g", "2": "kg", "3": "L", "4": "mg/ud", "5": "ml", "6": "cc" } as Record<string, string>)[value] || ""; }
function Card({ value, label }: { value: number; label: string }) { return <div className="card"><b>{value}</b><span>{label}</span></div>; }
function Fields({ children }: { children: React.ReactNode }) { return <div className="fields">{children}</div>; }
function Saved({ title, description, onNew, children }: { title: string; description: string; onNew?: () => void; children: React.ReactNode }) { return <div className="saved"><div className="saved-title"><h2>{title}</h2>{onNew && <button onClick={onNew}>Nuevo</button>}</div><p>{description}</p>{children}</div>; }
function List<T extends { id: string }>({ items, text, edit, remove }: { items: T[]; text: (value: T) => string; edit?: (value: T) => void; remove: (value: T) => void }) { return <ul>{items.map((item) => <li key={item.id}><span>{text(item)}</span>{edit && <button onClick={() => edit(item)}>Editar</button>}<button className="delete" onClick={() => remove(item)}>Eliminar</button></li>)}</ul>; }
function ResponsibleEditor({ value, save }: { value: Responsible; save: (value: Responsible) => void }) { const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); return <form onSubmit={(event) => { event.preventDefault(); save(draft); }}><h2>Persona comunicadora</h2><Fields><label>Nombre<input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>NIF<input required value={draft.nif} onChange={(event) => setDraft({ ...draft, nif: event.target.value })} /></label><label>Código ROPO<input required value={draft.ropo} onChange={(event) => setDraft({ ...draft, ropo: event.target.value })} /></label></Fields><button className="primary">Guardar</button></form>; }
function OwnerEditor({ value, save, cancel }: { value: Owner; save: (value: Owner) => void; cancel: () => void }) { const [draft, setDraft] = useState(value); const update = (field: keyof Owner, value: string | boolean | Land[]) => setDraft({ ...draft, [field]: value }); const updateLand = (landId: string, field: keyof Land, value: string) => update("lands", draft.lands.map((land) => land.id === landId ? { ...land, [field]: value } : land)); return <form className="editor" onSubmit={(event) => { event.preventDefault(); save(draft); }}><h2>{draft.name ? "Editar titular" : "Nuevo titular"}</h2><Fields><label>Nombre o razón social<input required value={draft.name} onChange={(event) => update("name", event.target.value)} /></label><label>NIF / CIF<input required value={draft.nif} onChange={(event) => update("nif", event.target.value)} /></label><label>Teléfono<input value={draft.phone} onChange={(event) => update("phone", event.target.value)} /></label><label>Correo<input type="email" value={draft.email} onChange={(event) => update("email", event.target.value)} /></label><label>Dirección<input value={draft.address} onChange={(event) => update("address", event.target.value)} /></label><label>Código postal<input value={draft.postalCode} onChange={(event) => update("postalCode", event.target.value)} /></label><label>Provincia INE<input value={draft.province} onChange={(event) => update("province", event.target.value)} /></label><label>Municipio INE<input value={draft.municipality} onChange={(event) => update("municipality", event.target.value)} /></label></Fields><label className="check"><input type="checkbox" checked={draft.hasRopo} onChange={(event) => update("hasRopo", event.target.checked)} /> Tiene ROPO propio</label><h3>Tierras SIGPAC</h3><p className="help">Añade cada recinto en una fila, con entre 0,5 y 1.000 ha. El código se exportará sin barras y no puede superar 20 caracteres.</p>{draft.lands.map((land) => <div className="land" key={land.id}><input required placeholder="Hectáreas" value={land.surface} onChange={(event) => updateLand(land.id, "surface", event.target.value)} /><input required placeholder="Código SIGPAC" value={land.location} onChange={(event) => updateLand(land.id, "location", event.target.value)} /><button type="button" className="delete" onClick={() => update("lands", draft.lands.filter((item) => item.id !== land.id))}>×</button></div>)}<button type="button" onClick={() => update("lands", [...draft.lands, { id: uid(), surface: "", location: "" }])}>Añadir tierra</button><p><button className="primary">Guardar titular</button> <button type="button" onClick={cancel}>Limpiar</button></p></form>; }
function ProductEditor({ value, save, cancel }: { value: Product; save: (value: Product) => void; cancel: () => void }) { const [draft, setDraft] = useState(value); const update = (field: keyof Product, value: string) => setDraft({ ...draft, [field]: value }); return <form className="editor" onSubmit={(event) => { event.preventDefault(); save(draft); }}><h2>{draft.name ? "Editar producto" : "Nuevo producto"}</h2><Fields><label>N.º de registro<input required value={draft.registration} onChange={(event) => update("registration", event.target.value)} /></label><label>Nombre comercial<input required value={draft.name} onChange={(event) => update("name", event.target.value)} /></label><label>Lote<input required value={draft.lot} onChange={(event) => update("lot", event.target.value)} /></label><label>Dosis por hectárea<input required inputMode="decimal" placeholder="Ej. 1,5" value={draft.dosePerHa} onChange={(event) => update("dosePerHa", event.target.value)} /></label><label>Unidad obligatoria<select required value={draft.unit} onChange={(event) => update("unit", event.target.value)}><option value="1">Gramos (g)</option><option value="2">Kilogramos (kg)</option><option value="3">Litros (L)</option><option value="4">Miligramos/unidades</option><option value="5">Mililitros (ml)</option><option value="6">Centímetros cúbicos (cc)</option></select></label></Fields><p className="help">La unidad es obligatoria en el formato oficial RT0001. El volumen total se calcula al registrar la aplicación.</p><button className="primary">Guardar producto</button> <button type="button" onClick={cancel}>Limpiar</button></form>; }
